### ISSUE TITLE
Meeting Series "Invited Editor" => sometimes adds user more than once to active minutes

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#293] opened 2017-07-18 17:53 UTC
This happened sporadically after the "Inform user about role change" user story was merged

Try to find steps to reproduce!

**Comment by migerh** [comment] 2017-07-18 20:34
![minutes](https://user-images.githubusercontent.com/368715/28338415-2992fdce-6c09-11e7-94f1-872b4cd2fad3.png)
![mongodb](https://user-images.githubusercontent.com/368715/28338416-2994b98e-6c09-11e7-9d7e-92ce58c4e2c8.png)

**Comment by woestmannje** [comment] 2017-07-20 10:01
Team estimation: 1-2d

**Comment by symonra** [comment] 2017-08-19 15:40
A way to reproduce the bug is by 
1) Adding a user as informed and saving 
2) Change his role to any other than informed 
then he will show up twice

I will look into the bug and try to solve it

**Comment by ampasc** [comment] 2017-09-01 18:00
After further analyzation of this issue I came to following insights:

When the error of duplicate users occurs, the participants that the app tried to write to mongo seems to be fully correct with no duplicate users.
However it appears there always happen 2 nearly synchronous updates of the participants list, each trying to add the new participants. It seems this leads to a chance of Mongo messing up the minutes' document and add users twice.

This synchronous calls seem to occur due to Meteor's optimistic-UI. Looking at the function call order this gets clear:
1. Code starts within the MeetingSeries-Editor-Template
2. Within the MeetingSeries class the function setVisibility is called
3. Within the Minute class the function SyncVisibility is called
4. Now the Meteor Method syncVisibility is called. Due to the optimistic UI all of the following code is executed both on server and client.
5. The Minute class's function refreshParticipants is called
6. The Minute class's function update is called
7. Finally the Meteor Method minute.update is called, in which the MongoCollection is updated. Hence the OptimisticUI this Meteor-Method-Call is done both by server and by client. This leads to the server trying to execute this method 2 times parallel.

This last duplicate call seems to trigger the error. 
By surpressing the redundant call from the server the error seems to disappear:

`if (Meteor.isClient) { 
	await Meteor.callPromise ('minutes.update', docPart, callback); 
} `

In order to reproduce the error you can try to run the following e2e-Test
`import { E2EGlobal } from './helpers/E2EGlobal';
import { E2EApp } from './helpers/E2EApp';
import { E2EMeetingSeries } from './helpers/E2EMeetingSeries';
import { E2EMinutes } from './helpers/E2EMinutes';
import { E2EMeetingSeriesEditor } from './helpers/E2EMeetingSeriesEditor';
import { E2EMinutesParticipants } from './helpers/E2EMinutesParticipants';

describe('MeetingSeries', function () {
    beforeEach("goto start page and make sure test user is logged in", function () {
        E2EApp.gotoStartPage();
        expect (E2EApp.isLoggedIn()).to.be.true;
    });

    before("reload page and reset app", function () {
        E2EApp.resetMyApp(true);
        E2EApp.launchApp();
    });

    it('DuplicateUsers-TEST-SERIES @watch', function () {
        //This test will create a MS and a Minute as User1
        //Then it will iterate the following steps: Add User2 as informed, promote User2 to invited, remove User2
        this.timeout(6000000);
        let aProjectName = 'DEKA';
        let aMeetingName = 'DEKA';
        E2EMeetingSeries.createMeetingSeries(aProjectName, aMeetingName);
        let msid = E2EMinutes.addMinutesToMeetingSeries(aProjectName, aMeetingName);

        let counter = 0;
        let user2 = E2EGlobal.SETTINGS.e2eTestUsers[1];
        while(user2) {
            //User2: Informed
            E2EMeetingSeriesEditor.openMeetingSeriesEditor(aProjectName, aMeetingName, "invited");
            E2EMeetingSeriesEditor.addUserToMeetingSeries(user2, E2EGlobal.USERROLES.Informed);
            E2EMeetingSeriesEditor.closeMeetingSeriesEditor();  // close with save
            //User2: Invited
            E2EMeetingSeriesEditor.openMeetingSeriesEditor(aProjectName, aMeetingName, "invited");
            let roleSelector = "select.user-role-select";
            browser.selectByValue(roleSelector, E2EGlobal.USERROLES.Invited);
            E2EMeetingSeriesEditor.closeMeetingSeriesEditor();  // close with save
            //Check Error Occured
            let min = server.call('e2e.findMin',msid);
            let partcount = min.participants.length;
            if (partcount !== 2) { //Error happened
                counter += 1;
                console.log('____________________________________________' + counter);
                console.log(min.participants);
                console.log('____________________________________________');
            }
            console.log('BISHER #FEHLER:' +  counter);

            //User2: Remove
            E2EMeetingSeriesEditor.openMeetingSeriesEditor(aProjectName, aMeetingName, "invited");
            let usersAndRoles = E2EMeetingSeriesEditor.getUsersAndRoles(0,1,2);
            browser.elementIdClick(usersAndRoles[user2].deleteElemId);
            E2EMeetingSeriesEditor.closeMeetingSeriesEditor();  // close with save
        }
    });
});`

I let this test run for arround 2 hours, the error occured 14 times. With the surpression of the redundant call it did not appear in 1.5 hours once.
(This test can be run both in GUI and in headless mode. Errors occur on both ways)

Although the above shown surpression of the redundant call would fix the issue, this is of course more of a quick&dirty hotfix. 
Furthermore until now I haven't analyzed from which locations the minute class's update function is currently called. If there would be for example a code piece only running on the server and using the update-function it would cause errors to allow the meteor method call only on client.
Therefore this issue needs further inspection to find the best way to deal with it.

**Comment by migerh** [comment] 2017-09-14 10:31
A fix was merged. Since we did not exactly find the root cause but you said in your repeated tests the issue did no longer occur. So we will close this for now and observe if the issue occurs again.

**Closed by migerh** 2017-09-14 10:31 UTC
Labels: bug, Students
