### ISSUE TITLE
BUG: Reset password email

### ISSUE THREAD

**Issue by joeydc** [4minitz/4minitz#504] opened 2019-08-16 19:11 UTC
I'm currently using the docker version of 4minitz v1.5.2 behind an Nginx reverse proxy.
I did set ROOT_URL in the json setting file correctly, using the proper domain name.
Settings for the SMTP server are also working except for the password reset.
Emails are being sent but the _From_ email account, the _subject_ and the _link_ are incorrect.

Here's an email example when asking for a password reset:
```
From: Accounts Example [no-reply@example.com]
Sent: Thursday, August 15, 2019 3:44 PM
To: John Doe
Subject: How to reset your password on localhost:3100

Hello John Doe,

To reset your password, simply click the link below.

http://localhost:3100/#/reset-password/zj3RnfxZgXHkdjBg9kwTEyOoi-w4UR5B8-PMfzECvI8

Thanks.
```
Is this an issue or maybe I'm missing an email template somewhere I have to configure?

**Comment by tillchen** [comment] 2019-10-10 11:28
Same issue here. The localhost:3100 should be replaced with our domain.

**Comment by tillchen** [comment] 2019-10-10 12:47
I'm guessing this might be a bug:)?

**Comment by tillchen** [comment] 2019-10-10 12:54
Can you maybe mark the title to BUG? So that the developers will see this instantly. @joeydc

**Comment by if-Patrick** [comment] 2020-03-06 13:43
I have the same problem. And it also happens to the verification mails.

```
Hello xxx,

To verify your account email, simply click the link below.

http://localhost:3100/#/verify-email/qHw4llTSrg5V4QItaBoxMn21569nqNbKTgUcGkOWn31

Thanks.
```

**Comment by derwok** [comment] 2020-03-07 15:02
Strange issue. Could you plz. state if you use docker build or own build?
Could you check the console / log file server side for this line:
*** ROOT_URL: https://xxx.yyy.zzz

**Comment by if-Patrick** [comment] 2020-03-07 15:50
I followed the admin installation guide here: https://github.com/4minitz/4minitz/blob/develop/doc/admin/adminguide.md#docker-setup-on-linux-and-mac to install 4minitz to my docker setup. (There is an openproject docker running as well without any problems.)

The docker vm is not accessable directly from the internet. It is behind a proxy which uses an url something like https://xxx.yyy.de which points to the 4minitz docker installation.

I checked the console / log file server side for the mentioned line (*** ROOT_URL: https://xxx.yyy.zzz). It shows the correct (publicly accessable) url https://xxx.yyy.de that was set up in the settings by me.

**Comment by derwok** [comment] 2020-03-07 17:03
OK. Thats interesting. 
Could you please try 2 things:
1. With a user that has a valid eMail address: login to 4Minitz. Then create a meeting series, inside create a meeting, in the meeting create 1 topic. Then press "Send Agenda" button. Inside the EMail - at the very bottom there should be two links where also absolute URLs shall be in. Check if these URLs are correct? Or also with localhost?

2.) There is a second way to specify the ROOT_URL: From outside on your docker commandline like so:

```
docker run -e "ROOT_URL=https://4minitz.mydomain.com" -it --rm -v $(pwd)/4minitz_storage:/4minitz_storage -p 3100:3333 4minitz/4minitz
```

Could you give that a shot and report results from step 1.) and 2.)?
Thx. WOK

**Comment by felixble** [comment] 2020-03-07 18:31
I can report the same issue in my personal docker setup for 4minitz. Unfortunately step 2.) proposed by @derwok did not solve it in my case.

Additionally, I could reproduce this issue in our development environment by defining a custom `ROOT_URL` in our test settings and requesting a password by the login user interface.

The good news is that I could find a solution 👍 

See 98fb5545433a2d106dcc35d6ac71678bbdf77c31 for details 😉 I made the changes directly on `develop`.

@derwok or @migerh could one of you please have a short look at the commit 98fb5545433a2d106dcc35d6ac71678bbdf77c31 and verify that is solves this issue? I think you can close it afterwards. Thanks!

**Comment by derwok** [comment] 2020-03-07 18:36
Hi Felix! Thanx for stepping in!
The code looks convincing to me. But only "eye review", no runtime checking.

So, have you tried that fix inside a real docker image? And does it solve the issue there?
Or should I build and push a docker-develop image so you can try?

**Comment by felixble** [comment] 2020-03-07 19:55
Hi @derwok :-)

With my changes I could not reproduce this issue in my local dev environment anymore. So I assume it will fix it in the docker image, too. But I haven't verified this assumption yet.

It would be great if you could push a docker-develop image. With that I can try it tomorrow.

**Comment by derwok** [comment] 2020-03-08 15:23
OK, just built & pushed an unstable/develop image to github where your fix is included.
Launch with: 
`docker run -it --rm -v $(pwd)/4minitz_storage:/4minitz_storage -p 3100:3333 4minitz/4minitz:develop`
or - to be very precise:
`docker run -it --rm -v $(pwd)/4minitz_storage:/4minitz_storage -p 3100:3333  4minitz/4minitz:gitcommit-98fb5545`

**Comment by felixble** [comment] 2020-03-09 16:00
I just updated my docker 4minitz instance to use the latest `develop` image. With this version I cannot reproduce this bug anymore 👍

**Comment by derwok** [comment] 2020-03-09 16:11
Yeij! Thx for fixing and testing!
🙏🏻

**Closed as completed** 2020-03-09 16:12 UTC
Labels: bug

**Comment by derwok** [comment] 2020-03-09 16:14
For reporters: we currently plan to release the next version in April/May. 
For non mission critical usage you might consider going with the develop image just pushed to docker yesterday.

**Comment by BigBlockStudios** [comment] 2021-03-02 22:26
Is this still an issue - I am getting the same problem - users cannot verify accounts or recover passwords even if the localhost part is changed to the correct URL.

**Comment by engineerjoe440** [comment] 2024-02-16 17:24
Thanks for this chain! I was able to poke around with the same issue, and ended up finding that setting my image to `image: 4minitz/4minitz:gitcommit-1202f41f` in my `docker-compose.yml` (to avoid issues with `develop` updating) also worked, and that's marvelous. This is a cool project. Thank you!
