### ISSUE TITLE
Unable to send mails via mailgun - TypeError: Cannot read property 'post' of  undefined

### ISSUE THREAD

**Issue by RedYouMan** [4minitz/4minitz#468] opened 2018-10-08 10:17 UTC
Hi,
i am using mailgun for email. I have configured the domain and `4minitz_settings.json
A snippet of my 4minitz_settings.json is 

"//3": "below option configures if and how to send E-Mails",
    "email": {
        "//3.1": "Switch on/off E-Mail sending",
        "enableMailDelivery": true,
        "//3.2": "Choose one of the below mail deliver methods",
        "mailDeliverer": "mailgun",

"fallbackEMailSenderAddress": "noreply@yourdomain.com",
        "smtp": {
            "mailUrl": "smtp://postmaster@sandbox8560f461222d4517a668a043c72d5f6f.mailgun.org:21b6c12e$
        },
        "mailgun": {
            "apiKey": "4040800f243dc2d9ed87485f1b5a5efb-c8e745ec-90b5f2a3",
            "domain": "sandbox8560f461222d4517a668a043c72d5f6f.mailgun.org",
            "apiUrl": "https://api.mailgun.net/v3/sandbox8560f461222d4517a668a043c72d5f6f.mailgun.org"
        },

        "//3.6": "Send an e-mail with a verification token to new user when enableMailDelivery:true",
        "sendVerificationEmail": true,

        "//3.7": "Enable form to resend the verification token to users e-mail when enableMailDelivery$        "showResendVerificationEmailLink": true,

        "//3.8": "Enable form to perform user password reset when enableMailDelivery:true",
        "showForgotPasswordLink": true

When i try to send Agenda I have this message to video "OK Agenda was send to recipient successfully"
but the log shows the following error
Error: TypeError: Cannot read property 'post' of  undefined

**Comment by RedYouMan** [comment] 2018-10-10 17:53
I use 4minits in Docker on Windows 10 behind a proxy. 
For proxy i use NTLMAPS configured and Docker configured in Settings Proxies

**Comment by derwok** [comment] 2018-11-25 18:50
Sorry for late answer...
Is this problem still persistent or could you solve it in the meantime?

**Comment by derwok** [comment] 2018-12-09 11:20
Will close as won't fix.
Please reopen if issue becomes active/interesting again.

**Comment by tillchen** [comment] 2019-04-02 20:21
I have the same problem @derwok

**Comment by tillchen** [comment] 2019-04-02 20:22
Here is my snippet for my settings

 "//3": "below option configures if and how to send E-Mails",
    "email": {
        "//3.1": "Switch on/off E-Mail sending",
        "enableMailDelivery": true,
        "//3.2": "Choose one of the below mail deliver methods",
        "mailDeliverer": "mailgun",

        "//3.3": [
            "defaultEMailSenderAddress: if this is an empty string, the sending users mail address will",
            "be the 'FROM:' sender of the email. If you specify an email address here, this mail address",
            "will be the 'FROM:' sender of each mails, and the sending user will be inserted to the 'REPLY-TO:' field",
            "If you set this to empty, please specify fallbackEMailSenderAddress!",
            "(see admin guide for the decision tree)."
        ],
        "defaultEMailSenderAddress": "",

        "//3.4": [
            "defaultEMailSenderExceptionDomains: an array of domains.",
            "For these domains the defaultEMailSenderAddress will NOT be used.",
            "Use case: Inside your intranet you want to send mails from real user names of you company.",
            "But if you cooperate with users from other companies inside your 4Minitz, these",
            "users will get trouble sending mail from your 4Minitz to mail addresses",
            "inside their company with their mail address in FROM: header.",
            "This really looks like spam, so it will probably be blocked!."
        ],
        "defaultEMailSenderExceptionDomains": ["yourdomain.de", "yourdomain.com"],

        "//3.5": [
                "fallbackEMailSenderAddress: if sending user has no mail address specified in the user profile,",
                "this will be 'FROM:' sender.",
                "If defaultEMailSenderAddress is set empty this field must be set with a valid email address.",
                "If this setting is empty and user has no mail address in profile, sending eMail will fail!",
                "(see admin guide for the decision tree)."
            ],
        "fallbackEMailSenderAddress": "ti.chen@jacobs-university.de",

        "mailgun": {
            "apiKey": "7a0fb41568c517dd58ad2d6ab2063beb-de7062c6-00c1b54d",
            "domain": "minitz.jacobs.university",
            "apiUrl": "https://api.mailgun.net/v3/minitz.jacobs.university"
        },

        "//3.6": "Send an e-mail with a verification token to new user when enableMailDelivery:true",
        "sendVerificationEmail": false,

        "//3.7": "Enable form to resend the verification token to users e-mail when enableMailDelivery:true",
        "showResendVerificationEmailLink": false,

        "//3.8": "Enable form to perform user password reset when enableMailDelivery:true",
        "showForgotPasswordLink": true
    },

**Comment by felixble** [comment] 2019-04-07 11:19
I am happy to announce that I could identify the main causes of this issue 👍.

1) Unfortunately, meteor has changed its api to send post requests. We have to use `HTTP.post` instead of `Meteor.http.post` now (see https://docs.meteor.com/api/http.html#HTTP-post) .

2) @RedYouMan and @tillchen please pass as `apiUrl` only the first part without your domain. So the `apiUrl` is `https://api.mailgun.net/v3` in all cases.

I will create a pull request to solve the first cause.

**Comment by tillchen** [comment] 2019-04-07 11:43
@felixble Hi:) Thank you for your reply! I changed the apiUrl to https://api.mailgun.net/v3 and tried to send the email again, but apparently the same problem persists. So maybe the problem is not from the apiURL?

Thank you!

**Comment by felixble** [comment] 2019-04-07 11:47
@tillchen yes and no ;-). The apiUrl is not the only problem. I just published a PR (see #495) to solve the second cause for this issue.

Unfortunately, you have to wait for the next release. Then it should work (if you set the apiUrl to https://api.mailgun.net/v3)

**Comment by tillchen** [comment] 2019-04-07 12:43
@felixble  Thank you so much:)

**Closed as completed** 2019-04-07 20:44 UTC
Labels: bug

**Comment by derwok** [comment] 2019-04-08 05:21
Thx Felix for taking care!
I will try to publish a new bugfix release this week... we have quite some important stuff in the pipeline now!

**Comment by derwok** [comment] 2019-04-23 21:44
Hey @RedYouMan 
I just published an "unstable" docker image from our current develop branch.
So could you please do a 
`docker run -it --rm -v $(pwd)/4minitz_storage:/4minitz_storage -p 3100:3333 4minitz/4minitz:unstable` 
and check if with this "beta version" your MailGun now works? Please report back here.
Hint: Important is the "unstable" at the end of the command line.

**Comment by tillchen** [comment] 2019-04-24 09:24
@derwok Hi! I tried to run the docker command above. But I received the error message:

docker: Error response from daemon: driver failed programming external connectivity on endpoint stoic_cray (72823e4cbd9e3fb66a80f25b28521e006541dc0709e0e0c838b5e695025428ea): Bind for 0.0.0.0:3100 failed: port is already allocated.

I think maybe I can't have the stable version and the unstable version at the same time for the same port. So should I maybe change the port number to resolve this:)?

Thank you!

**Comment by BigSnicker** [comment] 2020-07-07 15:16
For anyone else running into this problem, the unstable version does correct the mailgun access issue, and the relevant format for 4minitz_settings.json now looks like this:

        "mailgun": {
            "apiKey": "key-1a0a1a2b3c4d536f7a8b9c0da201",
            "domain": "mydomain.com",
            "apiUrl": "https://api.mailgun.net/v3"
        },
