### ISSUE TITLE
Performance issue: Participant checkbox

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#83] opened 2016-06-24 14:10 UTC
IT seems that if a meeting is loaded with topics and potential participants that the participant checkbox has a performance problem.

It takes up to 10 sec. that the local checkbox is changed. Other connected clients are faster!

**Comment by migerh** [comment] 2016-06-26 16:01
I had a look at this and I think this is caused by the generous distribution of
    $.material.init();
throughout the code base.

I will use this snippet 

https://raw.githubusercontent.com/ruidfigueiredo/findHandlersJS/master/findEventHandlers.js

to check the number of event handlers attached to the present status checkbox. Just copy & paste the code into the debug console once the site has finished loading and then execute

    findEventHandlers('change', '#btnTogglePresent')[0].events.length

to get the number of event handlers.

First, try to reproduce the problem on develop:
* Set up a meeting series
* Set up a minute
* Check the number of event handlers attached to the checkbox (will be something around 20-50)
* Add a topic, insert an action item into that topic
* Check/uncheck that action item many, many times.

Every time the action item is checked/unchecked, the minutes document is changed on the server and re-published to the client. And every time the template 'minutesEditParticipants' is re-rendered. And every time the number of event handlers is increased. Once it hits thousands, the delay will be noticeable. At some point it will take /seconds/ to fully process all attached eventhandlers.

I then deactivated all of $.material.init()s (see branch research/checkbox). If you then reload the page and repeat the steps above (just add a $.material.init() via the debug console once the minute is created to enable the checkboxes) you will observe that the number of event handlers no longer increases.

We need to look into $.material.init(), what it does and how we use it efficiently, without attaching thousands of event handlers to our elements. Maybe this is a bug in bootstrap-material-design?

**Comment by migerh** [comment] 2016-06-26 18:44
The culprit is identified:

The ```detailsArray()``` helper function in ```client/templates/topic/topicInfoItems.js``` calls

    $.material.init()

every time the minutes document is changed. What is this call for exactly?

But this only fixes the most pressing issue. The other ```$.material.init()``` calls need to be addressed as well. We either have to prevent the addition of unnecessary evedsnt handlers or need to take better care of disposing these event handlers. Maybe uzairfarooq/arrive can help with this?

**Comment by derwok** [comment] 2016-06-26 19:19
Hey Michael,
great analysis! Thanks!
I checked the event handlers with your snippet on /develop and on your branch - really surprising how fast these event handlers grow. WOW!  :-(

The initial call to ```$.material.init()``` in the ```onRendered()``` methods is mandatory IMHO.
So we can focus on the remaining other ```$.material.init()``` calls.

And here one more thought:
Maybe it would help to not call only ```$.material.checkbox()``` here - as suggested here:
https://github.com/FezVrasta/bootstrap-material-design#functions

I looked at the $.material.init() implementation of BMD project here:
https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L296

But I can see no "change" event handlers there...

**Comment by migerh** [comment] 2016-06-28 20:23
The fixes on [research/checkbox](https://github.com/4minitz/4minitz/tree/research/checkbox) look promising so far. It seems like everything works, but there is still the occasionally failing test. Some I can't explain, e.g. ```an add a responsible from the participant users``` and ```can add a responsible from user collection that is not a participant``` in ```TopicsResponsibles-test.js```. They fail regularly in end2end tests, but when the same is done by a user in a browser it works all the time.

A short summary of what has happened:

Replace the bootstrap, bootstrap-datetimepicker (bdp), and bootstrap-material-design (bmd) meteor packages with npm modules and properly initialize them in client/main.js. bmd already supports reactive clients by using [arrive.js](https://github.com/uzairfarooq/arrive). Unfortunately, bmd does not explicitly depend on arrive.js but will configure it if it is there. All we have to do is load arrive.js before bmd and initialize bmd _once_ as soon as the dom is ready. This is all done in [client/main.js](https://github.com/4minitz/4minitz/blob/99b85ae/client/main.js). 

To get it all running, it is important to use the exact same version of jQuery that bdp uses (see [package.json](https://github.com/4minitz/4minitz/blob/99b85ae2/package.json#L41)). If we do not add this package in the correct version, npm will download a separate copy for bdp which will be loaded only for this module. This causes the datetimepicker() jQuery extension to be added only to this jQuery instance, but not the global instance used by the meteor application. Also, the jQuery instance used by meteor is too old for bootstrap. Luckily, if we add jquery as a dependency in package.json, a copy will be downloaded into the node_modules/ folder. Meteor sees that copy and replaces its own copy of jQuery with this one. If we choose the same version bdp uses, npm will not download a separate copy for bdp into _node_modules/bootstrap-datetimepicker/node_modules_ but instead use the one in _node_modules/jquery_ when loading bdp.

Another issue were the missing fonts. Meteor apparently cannot load fonts from node_modules so I added a postinstall script to package.json that copies the corresponding files to public/fonts. These files are listed in .gitignore. In case some meteor installation complains about missing fonts, run

    $ npm install

or 

    $ npm run postinstall

and the issue should be fixed.

**Closed** 2016-06-30 18:25 UTC
Labels: bug, in progress
