### ISSUE TITLE
Create new Minutes directly from within latest finalized Minutes

### ISSUE THREAD

**Issue by fd0cwp** [4minitz/4minitz#448] opened 2018-06-19 06:58 UTC
Hi all,

I often run into the issue that I have opened the latest meeting minutes which is already finalized. So I am not able to add information (e.g. when I worked on an action item and I would like to note down the result as a new detail item of the action item). 
To be able to do this, I have to go to the minutes overview and create a new minutes there (which of course is not much effort but somehow annoys me).

It would be nice to have the possibility to create the next meeting minutes directly in the latest finalized meeting minutes.
This would also be helpful when you just finalized the minutes and you want to set up the next minutes right away.

As a suggestion, you might have at the top of the minutes beside the “Previous” link also the “Next” link (like for previous minutes) which does not show a date (because there is none yet :-)) but something like “create new minutes”. Clicking on this link shall then work in the same way as the button in the meeting minutes overview.

Best regards, Christoph

**Comment by derwok** [comment] 2018-07-31 20:22
I find the proposed solution very good. 
Let's see if we can implement this:

As a moderator I want to create new minutes directly from the latest minutes view so that I can speed up my workflow.

Acceptance Criteria:
1. Feature only available on latest meeting minutes
1. Feature only available if latest meeting minutes are finalized
1. Feature only available if user has moderator role
1. No button but clickable link text: "Create New Minutes"
1. After new minutes are created, the above link text changes to: "Next: YYYY-MM-DD" with clickable date

**Comment by fd0cwp** [comment] 2018-08-05 12:37
I would change 5 a little bit. After creating new minutes, I would like to have this new minutes opened directly to be able to edit it immediately.

**Comment by derwok** [comment] 2018-12-09 18:14
I would agree with @fd0cwp - we should jump to new minutes on acceptance criteria#5.
And I would add acceptance criteria 6: 

6. After click on "Create New Minutes" on the minutes view (only!) a security question "Do you really want to create new minutes?" [Yes/No] should prevent the user from accicently create new minutes.
**Rationale:** When user navigates a longer sequece of minutes just by clicking the "Next: YYYY-MM-DD" link multiple times, on the last minutes this link surprisingly changes to "Create New Minutes". So it may happen that the user creates the new minutes without intention. Security question shall prohibit this.

**Comment by felixble** [comment] 2020-03-11 07:45
Unfortunately, the solution merged with PR #520 doesn't work anymore as expected. The link "Create New Minutes" exists on the minutesedit page of the latest minutes. If you click this link a new minutes will be created but the open topics won't be copied 😕

**Comment by felixble** [comment] 2020-03-11 08:11
I cannot explain why this bug didn't appear when developing this feature 🤷‍♂ but I can explain the cause: When creating new minutes we collect the topics associated with the meeting series from the topics collection. On the `meetingSeriesDetails`-Template we have an active subscription on this collection which we don't have on the `minutesedit`-Template.

A quick fix could be adding the line `this.subscribe('topics', meetingSeriesId);` when doing the subscription on the  `minutesedit`-Template:

https://github.com/4minitz/4minitz/blob/8de5a8c9cbf9994dc13b9c469cfc6c3a56a8150e/client/templates/minutes/minutesedit.js#L161

I am not sure if it is a good idea to prepare the new minutes on the client side 🤔 

What do you think @derwok

**Comment by felixble** [comment] 2020-04-10 09:41
I opened two PRs:
* #545 Added a subscription to the topics collection from the minutesedit template
* #546 Moved the topics preparation for new minutes within the meteor method

Both solves the issue mentioned in my last comment. @derwok & @migerh which solution do you prefer?

**Comment by derwok** [comment] 2020-04-14 06:33
... was more complicated than expected....  :-)
Thx Felix!

**Closed as completed by derwok** 2020-04-14 06:33 UTC
Labels: bug, enhancement, Students
