### ISSUE TITLE
Send Agenda with Demo user => Internal Server Error

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#286] opened 2017-07-18 17:43 UTC
We go for a more general solution here - we see this 1.0 relevant.
Harden Mail sending: if users have no mail address or SMPT server reports problem: continue sending to other users.

**Comment by felixble** [comment] 2017-09-15 09:28
On a private server I have running a 4minitz instance tagged with v0.12.0-develop (commit: 17e0a9a). I activated the demo user and set the settings `trustedIntranetInstallation` to false.

My findings:
- Sending an agenda of a minutes with two participants (a normal user with an email address and the demo user without an email address) works perfectly: One E-Mail was sent
- If additionally a valid email address is entered in the additional participants field the document generation as well as the email sending operation will be canceled with an Internal Server Error. But this bug seems to be fixed on our current develop branch since I cannot reproduce this bug on our develop instance running on develop.4minitz.com

**Comment by felixble** [comment] 2017-09-15 12:09
I split this issue into two separate ones. The email hardening will be done after our v1.0 release (see #329). To close this issue we should at least make sure that the demo user becomes a dummy mail address.

**Comment by felixble** [comment] 2017-09-15 18:46
Update: we decided to close this issue since we do not want to give the demo user an email address and we could not reproduce this error anymore.

**Closed by felixble** 2017-09-15 18:46 UTC
Labels: bug
