### ISSUE TITLE
Error: TypeError: Cannot read property 'post' of undefined

### ISSUE THREAD

**Issue by tillchen** [4minitz/4minitz#492] opened 2019-04-02 20:24 UTC
Hi!

I encountered a problem while trying to send the agenda by email in 4minitz (docker). When I click send, the email won't be sent and the log says Error: TypeError: Cannot read property 'post' of undefined. 

Below is my setting:)
```
 "//3": "below option configures if and how to send E-Mails",
    "email": {
        "//3.1": "Switch on/off E-Mail sending",
        "enableMailDelivery": true,
        "//3.2": "Choose one of the below mail deliver methods",
        "mailDeliverer": "mailgun",

        "//3.3": [
            "defaultEMailSenderAddress: if this is an empty string, the sending users mail address will",
            "be the 'FROM:' sender of the email. If you specify an email address here, this mail address",
            "will be the 'FROM:' sender of each mails, and the sending user will be inserted to the 'REPLY-TO:' field",
            "If you set this to empty, please specify fallbackEMailSenderAddress!",
            "(see admin guide for the decision tree)."
        ],
        "defaultEMailSenderAddress": "",

        "//3.4": [
            "defaultEMailSenderExceptionDomains: an array of domains.",
            "For these domains the defaultEMailSenderAddress will NOT be used.",
            "Use case: Inside your intranet you want to send mails from real user names of you company.",
            "But if you cooperate with users from other companies inside your 4Minitz, these",
            "users will get trouble sending mail from your 4Minitz to mail addresses",
            "inside their company with their mail address in FROM: header.",
            "This really looks like spam, so it will probably be blocked!."
        ],
        "defaultEMailSenderExceptionDomains": ["yourdomain.de", "yourdomain.com"],

        "//3.5": [
                "fallbackEMailSenderAddress: if sending user has no mail address specified in the user profile,",
                "this will be 'FROM:' sender.",
                "If defaultEMailSenderAddress is set empty this field must be set with a valid email address.",
                "If this setting is empty and user has no mail address in profile, sending eMail will fail!",
                "(see admin guide for the decision tree)."
            ],
        "fallbackEMailSenderAddress": "XXX@jacobs-university.de",

        "mailgun": {
            "apiKey": "XXX",
            "domain": "minitz.jacobs.university",
            "apiUrl": "https://api.mailgun.net/v3/minitz.jacobs.university"
        },

        "//3.6": "Send an e-mail with a verification token to new user when enableMailDelivery:true",
        "sendVerificationEmail": false,

        "//3.7": "Enable form to resend the verification token to users e-mail when enableMailDelivery:true",
        "showResendVerificationEmailLink": false,

        "//3.8": "Enable form to perform user password reset when enableMailDelivery:true",
        "showForgotPasswordLink": true
    },
```
Thanks!

**Comment by derwok** [comment] 2019-04-06 12:45
@felixble cloud you maybe have a look into the mailgun usage?
You tried this once successfully...

**Comment by felixble** [comment] 2019-04-07 11:05
This issue is a duplicate of #468. I will close this and and solve the older one.

@tillchen sorry, that we did not respond to your comment in #468. I think it was forgotten since the issue is closed. Next time please feel free to reopen the existing issue ;-)

**Closed as completed by felixble** 2019-04-07 11:05 UTC
Labels: duplicate
